---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: centos-stream-9
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  managedOptions:
    onDelete: detach
  resource:
    name: CentOS-Stream-GenericCloud-x86_64-9-20250331.0.x86_64
    content:
      diskFormat: qcow2
      download:
        url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-x86_64-9-20250331.0.x86_64.qcow2
        hash:
          algorithm: sha256
          value: 3fdb00bdd44c8a8f682831e9d234d9ba8c8fc7812f060e5dbc319aaea42c50c7
