# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: openstack-resource-controller
site_url: https://k-orc.cloud/
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Reference: reference.md
  - Development:
    - Design decisions: development/design-decisions.md
    - API contracts: development/api-contracts.md
    - Local development: development/local-development.md
    - Writing controllers: development/writing-controllers.md
repo_url: https://github.com/k-orc/openstack-resource-controller
extra:
  analytics:
    provider: p
    data_domain: k-orc.cloud
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k-orc/openstack-resource-controller
    - icon: fontawesome/brands/slack
      link: slack://channel?team=T09NY5SBT&id=C05G4NJ6P6X
hooks:
  - hooks.py
theme:
  name: material
  custom_dir: overrides
plugins:
  - search:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - redirects:
      redirect_maps:
        'getting_started.md': 'getting-started.md'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
