name: Apply labels in .github/labels.yaml
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
      - .github/workflows/ensure-labels.yaml
permissions:
  pull-requests: write

jobs:
  ensure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yaml
